### ISSUE TITLE
templates are not part of the gem package

### ISSUE THREAD

**Issue by mtmail** [neilturner77/s3_asset_sync#1]
When I manually open the https://rubygems.org/downloads/s3_asset_sync-0.1.2.gem (a gzip archive) it is missing the files from the `templates` directory.

Thus `rake s3_asset_sync:setup` fails

``` sh
cp /Users/abc/.rvm/gems/ruby-2.1.6/gems/s3_asset_sync-0.1.2/templates/s3_asset_sync.rb config/initializers/s3_asset_sync.rb
rake aborted!
```

```
find /Users/abc/.rvm/gems/ruby-2.1.6/gems/s3_asset_sync-0.1.2/
/Users/abc/.rvm/gems/ruby-2.1.6/gems/s3_asset_sync-0.1.2/
/Users/abc/.rvm/gems/ruby-2.1.6/gems/s3_asset_sync-0.1.2//lib
/Users/abc/.rvm/gems/ruby-2.1.6/gems/s3_asset_sync-0.1.2//lib/s3_asset_sync
/Users/abc/.rvm/gems/ruby-2.1.6/gems/s3_asset_sync-0.1.2//lib/s3_asset_sync/railtie.rb
/Users/abc/.rvm/gems/ruby-2.1.6/gems/s3_asset_sync-0.1.2//lib/s3_asset_sync/version.rb
/Users/abc/.rvm/gems/ruby-2.1.6/gems/s3_asset_sync-0.1.2//lib/s3_asset_sync.rb
/Users/abc/.rvm/gems/ruby-2.1.6/gems/s3_asset_sync-0.1.2//lib/tasks
/Users/abc/.rvm/gems/ruby-2.1.6/gems/s3_asset_sync-0.1.2//lib/tasks/s3_asset_sync.rake
/Users/abc/.rvm/gems/ruby-2.1.6/gems/s3_asset_sync-0.1.2//MIT-LICENSE
/Users/abc/.rvm/gems/ruby-2.1.6/gems/s3_asset_sync-0.1.2//Rakefile
/Users/abc/.rvm/gems/ruby-2.1.6/gems/s3_asset_sync-0.1.2//README.rdoc
```

(as workaround I will just download the template file from git manually)

**Comment by neilturner77** [comment]
@mtmail How are you installing this exactly? Via bundle install?

**Comment by mtmail** [comment]
yes, added to `Gemfile`, then `bundle install`. I think templates just need to be added to this line

`s.files = Dir["{app,config,db,lib}/**/*", "MIT-LICENSE", "Rakefile", "README.rdoc"]`

in the `.gemspec` file.

**Comment by neilturner77** [comment]
@mtmail Ah my bad :-) I've added that directory and bumped the version so 0.1.3 should hopefully be OK. I'm just testing it now and I'll confirm. Cheers!

**Comment by neilturner77** [comment]
@mtmail Yep that seems to work fine now.
